version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      SA_PASSWORD: "ef66b58b-6ff2-4c78-bcec-6b279312b625" 
      ACCEPT_EULA: "Y" 
      MSSQL_PID: "Developer" 
      MSSQL_COLLATION: "Latin1_General_CI_AS" 
      MSSQL_AGENT_ENABLED: "true" 
    ports:
      - "1433:1433"